#!/usr/bin/env python3
"""Python-first RAG decision state machine runner.

LangGraph is intentionally not used in this round. This runner makes the
designed graph executable with deterministic local dry-runs first.
"""

from __future__ import annotations

import argparse
import json
import pathlib
from typing import Any

import rag_common as common
import rag_weighted_decision_engine as decision_engine


DECISION_DIR = common.ROOT / "codex_log" / "rag_decision_engine"
FIXTURE_DIR = common.ROOT / "codex_source" / "fixtures" / "rag_decision_engine"
STATE_RUN_JSON = DECISION_DIR / "latest_decision_state_machine_run.json"
STATE_RUN_MD = DECISION_DIR / "latest_decision_state_machine_run.md"
TRACE_JSON = DECISION_DIR / "trace_event_20260621_rag_decision_state_machine_runner.json"

NODE_ORDER = [
    "task_classifier",
    "rag_vector_maintenance_router",
    "stale_index_checker",
    "vector_retriever_or_repo_readback",
    "source_readback_checker",
    "authority_overlay_filter",
    "conflict_group_resolver",
    "hard_gate_checker",
    "weighted_decision_engine",
    "decision_audit_reporter",
    "codex_supply_pack_emitter",
    "failure_router",
]


def _resolve(path_value: str) -> pathlib.Path:
    path = pathlib.Path(path_value)
    return path if path.is_absolute() else common.ROOT / path


def _load_case(case: str | None, case_path: str | None) -> dict[str, Any]:
    if case_path:
        return common.read_json(_resolve(case_path))
    if case:
        for subdir in ("state_machine", "decision_audit", "weighted_decision"):
            path = FIXTURE_DIR / subdir / f"{case}.json"
            if path.exists():
                return common.read_json(path)
    return {"case_id": "current_blocked_sync_decision_case", "task_request": {"task_type": "mechanism_repair", "risk_level": "high", "stale_index_usage": "reference_only_with_readback"}}


def _read_gate_report() -> dict[str, Any]:
    path = common.OUT_DIR / "latest_vector_sync_gate_report.json"
    return common.read_json(path) if path.exists() else {"status": "missing", "blocked_reasons": ["gate_report_missing"]}


def _source_commit(gate_report: dict[str, Any]) -> str:
    return str(gate_report.get("indexable_change_result", {}).get("source_commit_sha") or common.current_commit())


def _node(name: str, status: str, output: dict[str, Any], blocked_reason: str | None = None) -> dict[str, Any]:
    return {
        "node_name": name,
        "status": status,
        "output": output,
        "blocked_reason": blocked_reason,
        "finished_at": common.now_iso(),
    }


def emit_supply_packs(audit_report: dict[str, Any], *, source_commit_sha: str) -> dict[str, Any]:
    audit = audit_report["decision_audit_report"]
    common_fields = {
        "decision_audit_report_id": audit_report["decision_audit_report_id"],
        "hard_gate_result": audit["hard_gate_result"],
        "selected_action": audit["selected_action"],
        "can_feed_codex": audit["hard_gate_result"]["status"] == "passed",
        "can_claim_completed": False,
        "conflict_group_id": "rag_decision_engine_round_2",
        "source_commit_sha": source_commit_sha,
        "generated_at": common.now_iso(),
    }
    audit_snippet = {
        "source_path": "codex_log/rag_decision_engine/latest_decision_audit_report.json",
        "line_range": "json",
        "chunk_id": audit_report["decision_audit_report_id"],
        "readback": "Decision audit report generated by Python state machine dry-run.",
        "snippet": "Decision audit report generated by Python state machine dry-run.",
        "readback_hash_match": True,
        "file_hash_match": True,
        "authority_level": "current_repo_source",
        "stale_status": "current",
        "conflict_status": "none",
        "readback_required": True,
        "can_feed_codex": audit["hard_gate_result"]["status"] == "passed",
        "can_claim_completed": False,
    }
    pre = {
        "pack_type": "pre_supply_pack",
        "task_id": "rag-decision-engine-round2-python-state-machine",
        "task_type": audit["task_context"]["task_type"],
        "retrieval_goal": audit["task_context"]["question"],
        "exact_snippet_pack": [audit_snippet],
        "source_path": "codex_log/rag_decision_engine/latest_decision_audit_report.json",
        "line_range": "json",
        "chunk_id": audit_report["decision_audit_report_id"],
        "why_needed": "Codex must execute from decision audit evidence, not raw prompt intuition.",
        "execution_constraint": ["hard_gate_before_weight", "source_readback_required", "do_not_claim_RAG_latest"],
        "conflict_points": audit["conflict_groups_checked"],
        "cleaning_layer_check": {
            "authority_level": "current_repo_source",
            "stale_status": "current",
            "conflict_status": "none",
            "readback_required": True,
            "can_feed_codex": audit["hard_gate_result"]["status"] == "passed",
            "can_claim_completed": False,
            "status": "passed" if audit["hard_gate_result"]["status"] == "passed" else "blocked",
        },
        "blocked_if": ["hard_gate_failed", "conflict_pending_required_fact", "high_risk_stale_source_without_readback"],
        **common_fields,
    }
    mid = {
        "pack_type": "mid_task_supply_pack",
        "child_task_id": "rag-decision-state-machine-dry-run",
        "files_already_read": audit["readback_status"].get("source_paths", []),
        "will_modify_files": [],
        "missing_context": [],
        "validation_failure_logs": [],
        "conflict_points": audit["conflict_groups_checked"],
        "incremental_snippets": [],
        "action_constraint": ["continue_only_if_hard_gate_passed"],
        "continue_allowed": audit["hard_gate_result"]["status"] == "passed",
        "blocked_if": ["hard_gate_failed", "state_machine_node_failed"],
        **common_fields,
    }
    post = {
        "pack_type": "post_risk_review_pack",
        "task_id": "rag-decision-engine-round2-python-state-machine",
        "completion_truth_check": {
            "source_commit_sha": source_commit_sha,
            "current_RAG_index_latest_claim": False,
            "content_validation": "not_promoted",
            "production_readiness": "not_claimed",
            "langgraph_implemented": False,
        },
        "risk_points": audit["blocked_if"],
        "completion_allowed": False,
        "blocked_if": ["do_not_claim_production_ready", "do_not_claim_RAG_latest"],
        **common_fields,
    }
    common.write_json(common.OUT_DIR / "latest_pre_supply_pack.json", pre)
    common.write_json(common.OUT_DIR / "latest_mid_task_supply_pack.json", mid)
    common.write_json(common.OUT_DIR / "latest_post_risk_review_pack.json", post)
    return {"pre_supply_pack": pre, "mid_task_supply_pack": mid, "post_risk_review_pack": post}


def run_state_machine(case: dict[str, Any], *, dry_run: bool = True) -> dict[str, Any]:
    gate_report = _read_gate_report()
    source_commit_sha = _source_commit(gate_report)
    task_request = case.get("task_request", case)
    node_results: list[dict[str, Any]] = []

    task_context = {
        "task_type": task_request.get("task_type") or case.get("task_type") or "mechanism_repair",
        "risk_level": task_request.get("risk_level") or case.get("risk_level") or "high",
        "dry_run": dry_run,
        "langgraph_implemented": False,
    }
    node_results.append(_node("task_classifier", "passed", task_context))

    try:
        import rag_vector_maintenance_router as maintenance_router

        maintenance_decision = maintenance_router.build_decision({"task_context": task_context}, dry_run=True)
        maintenance_output = {
            "status": maintenance_decision["status"],
            "action_id": maintenance_decision["selected_action"]["action_id"],
            "action_label": maintenance_decision["selected_action"]["action_label"],
            "current_RAG_index_latest_claim_allowed": maintenance_decision["vector_health"]["current_RAG_index_latest_claim_allowed"],
            "external_api_called": False,
        }
        node_results.append(_node("rag_vector_maintenance_router", "passed", maintenance_output))
    except Exception as exc:  # pragma: no cover - defensive runtime route
        node_results.append(
            _node(
                "rag_vector_maintenance_router",
                "blocked",
                {"status": "blocked", "error": str(exc)[:240], "external_api_called": False},
                "rag_vector_maintenance_router_failed",
            )
        )

    stale = {
        "status": "stale_or_blocked" if gate_report.get("status") == "blocked" else "current_or_unknown",
        "current_RAG_index_latest_claim": False,
        "vector_sync_status": gate_report.get("vector_sync_status") or gate_report.get("status"),
        "allowed_usage": "reference_only_with_source_readback",
    }
    node_results.append(_node("stale_index_checker", "passed", stale))

    retrieval = {"status": "repo_readback_fallback", "external_query_called": False, "retrieved_candidates": []}
    node_results.append(_node("vector_retriever_or_repo_readback", "passed", retrieval))

    readback = {
        "status": "passed" if not task_request.get("source_readback_missing") else "blocked",
        "source_paths": [
            "codex_log/latest.md",
            "codex_log/rag_vector_sync/latest_vector_sync_gate_report.json",
            "codex_log/rag_decision_engine_design/20260621_RAG决策工程线设计_round_1_design_only.md",
        ],
    }
    node_results.append(_node("source_readback_checker", readback["status"], readback, "source_readback_missing" if readback["status"] == "blocked" else None))

    authority = {
        "status": "passed",
        "overlay_path": "codex_log/rag_decision_engine/latest_rag_authority_overlay.json",
        "stale_sources_can_feed_codex": False,
    }
    node_results.append(_node("authority_overlay_filter", "passed", authority))

    conflicts = {
        "status": "blocked" if task_request.get("conflict_pending_required_fact") else "passed",
        "registry_path": "codex_log/rag_decision_engine/latest_conflict_group_registry.json",
        "pending_conflicts": ["required_fact"] if task_request.get("conflict_pending_required_fact") else [],
    }
    node_results.append(_node("conflict_group_resolver", conflicts["status"], conflicts, "conflict_pending_required_fact" if conflicts["status"] == "blocked" else None))

    case_for_decision = {**case, "task_request": {**task_request, "stale_index_usage": "reference_only_with_readback"}}
    audit_report = decision_engine.build_decision_report(case_for_decision, gate_report)
    hard_gate = audit_report["decision_audit_report"]["hard_gate_result"]
    node_results.append(_node("hard_gate_checker", hard_gate["status"], hard_gate, hard_gate.get("blocked_reason") or None))

    if hard_gate["status"] == "passed":
        weighted = audit_report["decision_audit_report"]["weighted_score_breakdown"]
        node_results.append(_node("weighted_decision_engine", "passed", weighted))
    else:
        node_results.append(_node("weighted_decision_engine", "skipped", {"reason": "hard_gate_failed_before_weight"}, "hard_gate_failed_before_weight"))

    common.write_json(decision_engine.AUDIT_JSON, audit_report)
    decision_engine.write_markdown(audit_report, decision_engine.AUDIT_MD)
    node_results.append(_node("decision_audit_reporter", audit_report["validation_result"]["status"], {"path": decision_engine.AUDIT_JSON.as_posix(), "selected_action": audit_report["decision_audit_report"]["selected_action"]}))

    packs = emit_supply_packs(audit_report, source_commit_sha=source_commit_sha)
    node_results.append(_node("codex_supply_pack_emitter", "passed", {"pre_supply_pack": common.OUT_DIR.joinpath("latest_pre_supply_pack.json").as_posix(), "mid_task_supply_pack": common.OUT_DIR.joinpath("latest_mid_task_supply_pack.json").as_posix(), "post_risk_review_pack": common.OUT_DIR.joinpath("latest_post_risk_review_pack.json").as_posix()}))

    failure_route = "none" if hard_gate["status"] == "passed" and conflicts["status"] == "passed" and readback["status"] == "passed" else "human_decision_gate_or_RAG_sync_bus"
    node_results.append(_node("failure_router", "passed", {"failure_route": failure_route}))

    status = "passed" if audit_report["validation_result"]["status"] == "passed" and readback["status"] == "passed" and conflicts["status"] == "passed" else "blocked"
    result = {
        "manifest_type": "rag_decision_state_machine",
        "project_route": common.PROJECT_ROUTE,
        "repo_full_name": common.REPO_FULL_NAME,
        "source_commit_sha": source_commit_sha,
        "generated_at": common.now_iso(),
        "input_paths": [
            "codex_log/rag_vector_sync/latest_vector_sync_gate_report.json",
            "codex_source/fixtures/rag_decision_engine",
        ],
        "output_paths": [
            STATE_RUN_JSON.as_posix(),
            decision_engine.AUDIT_JSON.as_posix(),
            common.OUT_DIR.joinpath("latest_pre_supply_pack.json").as_posix(),
            common.OUT_DIR.joinpath("latest_rag_vector_maintenance_decision.json").as_posix(),
            TRACE_JSON.as_posix(),
        ],
        "case_id": case.get("case_id") or "current_blocked_sync_decision_case",
        "dry_run": dry_run,
        "no_external_api_default": True,
        "alibaba_embedding_api_called": False,
        "dashvector_upsert_called": False,
        "langgraph_implemented": False,
        "python_state_machine_implemented": True,
        "nodes": node_results,
        "selected_action": audit_report["decision_audit_report"]["selected_action"],
        "supply_packs": {
            "pre_supply_pack": "codex_log/rag_vector_sync/latest_pre_supply_pack.json",
            "mid_task_supply_pack": "codex_log/rag_vector_sync/latest_mid_task_supply_pack.json",
            "post_risk_review_pack": "codex_log/rag_vector_sync/latest_post_risk_review_pack.json",
        },
        "blocked_if": audit_report["blocked_if"],
        "validation_result": {"status": status},
        "key_printed": False,
        "key_written": False,
    }
    return result


def write_state_markdown(result: dict[str, Any], path: pathlib.Path = STATE_RUN_MD) -> None:
    lines = [
        "# RAG Decision State Machine Run",
        "",
        f"- status: `{result['validation_result']['status']}`",
        f"- case_id: `{result['case_id']}`",
        f"- selected_action: `{result['selected_action']}`",
        f"- dry_run: `{str(result['dry_run']).lower()}`",
        "- langgraph_implemented: `false`",
        "- alibaba_embedding_api_called: `false`",
        "- dashvector_upsert_called: `false`",
        "",
        "## Nodes",
        "",
    ]
    for node in result["nodes"]:
        lines.append(f"- `{node['node_name']}`: `{node['status']}`")
    common.write_markdown(path, lines)


def write_trace(result: dict[str, Any], path: pathlib.Path = TRACE_JSON) -> dict[str, Any]:
    trace = {
        "created_at": common.now_iso(),
        "event_id": "20260621_rag_decision_state_machine_runner",
        "event_type": "mechanism_repair_execution.rag_decision_state_machine_runner",
        "task_id": "rag-decision-engine-round2-python-state-machine",
        "input_signal": {"round_scope": "round_2_python_state_machine_first", "case_id": result["case_id"]},
        "files_modified": [
            "codex_log/rag_decision_engine/latest_decision_state_machine_run.json",
            "codex_log/rag_decision_engine/latest_decision_audit_report.json",
            "codex_log/rag_vector_sync/latest_rag_vector_maintenance_decision.json",
            "codex_log/rag_vector_sync/latest_pre_supply_pack.json",
            "codex_log/rag_vector_sync/latest_mid_task_supply_pack.json",
            "codex_log/rag_vector_sync/latest_post_risk_review_pack.json",
        ],
        "validation_result": {
            "status": result["validation_result"]["status"],
            "python_state_machine_implemented": True,
            "langgraph_implemented": False,
            "external_api_called": False,
            "dashvector_upsert_called": False,
            "selected_action": result["selected_action"],
        },
        "failure_route_if_any": None if result["validation_result"]["status"] == "passed" else "human_decision_gate_or_RAG_sync_bus",
        "next_safe_step": "Run validators and keep real delta sync pending controlled authorization.",
    }
    common.write_json(path, trace)
    return trace


def main() -> int:
    common.main_guard()
    parser = argparse.ArgumentParser(description="Run Python-first RAG decision state machine.")
    parser.add_argument("--dry-run", action="store_true", default=True)
    parser.add_argument("--case", default="current_blocked_sync_decision_case")
    parser.add_argument("--case-path")
    parser.add_argument("--out", default=str(STATE_RUN_JSON))
    parser.add_argument("--md-out", default=str(STATE_RUN_MD))
    args = parser.parse_args()

    result = run_state_machine(_load_case(args.case, args.case_path), dry_run=True)
    out_path = _resolve(args.out)
    md_path = _resolve(args.md_out)
    common.write_json(out_path, result)
    write_state_markdown(result, md_path)
    write_trace(result)
    print(
        json.dumps(
            {
                "status": result["validation_result"]["status"],
                "state_machine_run_path": out_path.as_posix(),
                "selected_action": result["selected_action"],
                "python_state_machine_implemented": True,
                "langgraph_implemented": False,
                "alibaba_embedding_api_called": False,
                "dashvector_upsert_called": False,
            },
            ensure_ascii=False,
            sort_keys=True,
        )
    )
    return 0 if result["validation_result"]["status"] == "passed" else 2


if __name__ == "__main__":
    raise SystemExit(main())
